### ISSUE TITLE
not complete project

### ISSUE THREAD

**Issue by hantertill** [mangonote-project/mangonote#1]
creeted new address mined 100 mangonote
after 1 day address creeted disapereed and nothing in wallet
one day lost thanks

**Comment by mangonote-devs** [comment]
@hantertill Try updating to the latest wallet version.
Then, inside the wallet-cli, run these commands:
```
set refresh-from-block-height 0
rescan_bc
```

Feel free to reopen if the issue persist after you run these commands.

**Comment by Saeed321** [comment]
I am facing the same problem and the below commands are not solving the problem.

```
set refresh-from-block-height 0
rescan_bc
```

Still showing 0 balance.
